version: '3'

services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile_mysql
    container_name: db
    restart: always
    tty: true
    # dump que cria a estrutura do banco, no caso, cria a tabela people
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    networks:
      - mysqlnet

  app:
    build: 
      context: .
      dockerfile: Dockerfile_node
    # utilizando o dockerize para esperar o container do banco para subir o container do app
    entrypoint: dockerize --wait tcp://db:3306 -timeout 20s node index.js
    container_name: app
    tty: true
    networks:
      - mysqlnet
    depends_on:
      - db

  proxy:
    build: 
      context: .
      dockerfile: Dockerfile_nginx
    entrypoint: dockerize --wait tcp://app:3000 -timeout 40s ./docker-entrypoint.sh nginx -g "daemon off;"
    container_name: proxy
    tty: true
    ports:
      - "8080:80"
    networks:
      - mysqlnet
    depends_on:
      - app

networks:
  mysqlnet:
    name: mysqlnet
    driver: bridge      