FROM nginx

# remove o arquivo de configuracao padrao
RUN rm /etc/nginx/conf.d/default.conf

# copia o arquivo de configuracao da aplicacao
COPY ./nginx_conf/nginx.conf /etc/nginx/conf.d

# atualizando os pacotes e instalando o wget para instalar o dockerize
RUN apt-get update && apt-get install -y wget

ENV DOCKERIZE_VERSION v0.6.1

# descompactando e instalando o dockerize
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

ENTRYPOINT [ "/docker-entrypoint.sh" ]

CMD [ "nginx -g", "daemon off;" ]

# CMD [ "nginx", "-g", "daemon off;" ]
